// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkQeLRtAo3mfysfegMs4tehVqreHAt9aM',
    appId: '1:187053087741:web:fcdd7d128bb32b429ad794',
    messagingSenderId: '187053087741',
    projectId: 'jobsapp-37cfb',
    authDomain: 'jobsapp-37cfb.firebaseapp.com',
    storageBucket: 'jobsapp-37cfb.appspot.com',
    measurementId: 'G-X0Q46EZGJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGUDsBrWImSpkINfpK6m6ywt2gfE-804o',
    appId: '1:187053087741:android:e15854547aeba2f09ad794',
    messagingSenderId: '187053087741',
    projectId: 'jobsapp-37cfb',
    storageBucket: 'jobsapp-37cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAN1FbKog0Lg65Z1ijWjYKtBnTiENB9j0',
    appId: '1:187053087741:ios:e38e122bca35e0419ad794',
    messagingSenderId: '187053087741',
    projectId: 'jobsapp-37cfb',
    storageBucket: 'jobsapp-37cfb.appspot.com',
    iosClientId: '187053087741-qksdh087ecd43hvsaodahltc6gd9s8u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAN1FbKog0Lg65Z1ijWjYKtBnTiENB9j0',
    appId: '1:187053087741:ios:e38e122bca35e0419ad794',
    messagingSenderId: '187053087741',
    projectId: 'jobsapp-37cfb',
    storageBucket: 'jobsapp-37cfb.appspot.com',
    iosClientId: '187053087741-qksdh087ecd43hvsaodahltc6gd9s8u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobsApp',
  );
}
